[package]
name = "ismism"
version = "1.0.0"
edition = "2021"
description = "A CLI tool which helps to open ismism videos quickly."
authors = ["awei"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
webbrowser = "0.8.4"
